version: "3.5"

services:
  bullboard:
    container_name: bullboard
    build:
      dockerfile: ./Dockerfile
      context: .
    restart: always
    ports:
      - 3000:3000
    environment:
      REDIS_HOST: host
      REDIS_PASSWORD: pass
